### ISSUE TITLE
Connection lost during search

### ISSUE THREAD

**Issue by kata62** [zombiB/zombi-addons#10]
Link deleted for security issue

**Comment by zombiB** [comment]
شكرا لك، اللوغ يظهر أن البحث لا يعمل في بعض المواقع الذي لا يصل اليها الجهاز قد تكون بسبب حظر أو حماية، جرب الدخول الى موقع الفحر مثلا من المتصفح

**Comment by kata62** [comment]
فعلا الموقع محظور
