### ISSUE TITLE
[BUG] Esseq website isn't working

### ISSUE THREAD

**Issue by Mr-7mdan** [zombiB/zombi-addons#105]
- Movies don't show
- No hosters for both Movies and Episodes
- @zombiB your help pls

**Comment by zombiB** [comment]
I will look at it when I get home, hopefully it is not complex

**Comment by zombiB** [comment]
لم أجد الوقت الكافي لإصلاح قسم الأفلام لكن عند تجربة المسلسلات الروابط تظهر و تشتغل

**Comment by zombiB** [comment]
تم تحديث قسم الأفلام
