### ISSUE TITLE
Universal Search results 

### ISSUE THREAD

**Issue by zombiB** [zombiB/zombi-addons#106]
البحث الشامل يعمل لكن النتائج لا تظهر

**Comment by Mr-7mdan** [comment]
ساقوم بالمتابعة ان شاء الله

**Comment by aouamed** [comment]
فعلا اخي هدا ما وقع معي...لكن في البحث الغير شامل يعمل

**Comment by Mr-7mdan** [comment]
الغريب قمت بالغاء Matrix Cache من الكود بشكل كامل وحذف التعديلات الخاصه به. ولا زال البحث الشامل لا يعمل يقوم بالبحث ولا يظهر النتائج
الـ log لا يوضح وجود اي خطأ. حيرني الامر

**Comment by Mr-7mdan** [comment]
تم اكتشاف المشكلة وحلها الان البحث الشامل يعمل بشكل طبيعي
https://github.com/zombiB/zombi-addons/commit/a53f9c9b7b07b1c2d099a67278ab3f4ce7a70c0c
كانت المشكلة في مكان وجود oGui.setEndOfDirectory في بعض المواقع

**Comment by nidaltiti** [comment]
شكرا شباب

**Comment by nidaltiti** [comment]
البحث الشامل يعمل لكن النتائج لا تظهر   لماذا
