### ISSUE TITLE
[Question] hosters

### ISSUE THREAD

**Issue by Mr-7mdan** [zombiB/zombi-addons#107]
اخي الكريم @zombiB 
في اضافة vstream ارى ان الكثير من الـ hosters تم تحديثهم.
هل قمت بجلب التحديثات لماتركس سابقاً ؟ 
الاحط ان هناك بعض الامور لمعالجة ال cloudfare وتفعيل لل flare resolver لبعض المواقع. 
هل يمكن الاستفادة من هذه التحديثات لديهم؟

**Comment by zombiB** [comment]
انا أنقل تحديثات vstream كل فترة، flaresolver يعمل في ماتريكس مثل vstream فقط مؤخرا قاموا باضافة إعدادات لتفعيل او الغاء مواقع المحجوبة بكلاوفلاير
بالنسبة للhosters هي محدثة

**Comment by Mr-7mdan** [comment]
لاحظت ان روابط mega و rapidgator مثلا منتشرة جداً ولا يوجد لها هوستر. 
مع ان mega لديه هوستر ولكن لا يعمل على ما يبدو و  rapidgator   يجب ان يعمل من خلال real-debrid h او alldebrid ولكن cHoster يقوم برفض الرابط.

**Comment by Mr-7mdan** [comment]
سؤال اخر، قمت باضافة 3 مواقع مؤخراً وقمت بجعل الاقسام يتم تحميلها كل مرة لتجنب تعطل روابط الاقسام ولجلب اي اقسام جديدة في المواقع. ولكن الان الاحظ ان المواقع لا تظهر كخيارات من الصفحة الرئيسية 
Matrix - > TV Shows - > (((هنا تظهر المواقع التي بها هذا القسم))))
فهذه الاقسام لا تظهر بالشكل اعلاه. على ما يبدو يجب ان اقوم باعادة كتابتها بطريقة ثابتة كالمواقع الاخرى. 
هل استنتاجي صحيح؟

**Comment by zombiB** [comment]
> سؤال اخر، قمت باضافة 3 مواقع مؤخراً وقمت بجعل الاقسام يتم تحميلها كل مرة لتجنب تعطل روابط الاقسام ولجلب اي اقسام جديدة في المواقع. ولكن الان الاحظ ان المواقع لا تظهر كخيارات من الصفحة الرئيسية
> 
> Matrix - > TV Shows - > (((sites that have this section)))) فهذه الاقسام لا تظهر بالشكل اعلاه. على ما يبدو يجب ان اقوم باعادة كتابتها بطريقة ثابتة كالمواقع الاخرى. هل استنتاجي صحيح؟

كلامك صحيح فمثلا عندما أصبح موقع سيمافوريو يغير روابط الاقسام بشكل دوري حذفت الاقسام و لم يعد يظهر الموقع في اقسام ماتريكس، يمكنك ان تجرب جعل الرابط يظهر بصفة آلية لكن لا أعرف اذاكان سيسبب بطئ الاضافة يجب أن نجرب و نحكم

**Comment by Mr-7mdan** [comment]
> > سؤال اخر، قمت باضافة 3 مواقع مؤخراً وقمت بجعل الاقسام يتم تحميلها كل مرة لتجنب تعطل روابط الاقسام ولجلب اي اقسام جديدة في المواقع. ولكن الان الاحظ ان المواقع لا تظهر كخيارات من الصفحة الرئيسية
> > Matrix - > TV Shows - > (((sites that have this section)))) فهذه الاقسام لا تظهر بالشكل اعلاه. على ما يبدو يجب ان اقوم باعادة كتابتها بطريقة ثابتة كالمواقع الاخرى. هل استنتاجي صحيح؟
> 
> كلامك صحيح فمثلا عندما أصبح موقع سيمافوريو يغير روابط الاقسام بشكل دوري حذفت الاقسام و لم يعد يظهر الموقع في اقسام ماتريكس، يمكنك ان تجرب جعل الرابط يظهر بصفة آلية لكن لا أعرف اذاكان سيسبب بطئ الاضافة يجب أن نجرب و نحكم

ساعمل على تعديل المواقع لتظهر . بخصوص البطء ، لا اعتقد ان يؤدي الى بطىء بسبب وجود Matrix Cache. خصوصاً انه من خلال الكود نستطيع جعل كاش الاقسام مثلا صالح ليوم او يومين او اسبوع . مما يعني ان تحميل الاقسام لن يكون في كل عملية تشغيل.
