### ISSUE TITLE
قسم البث المباشر 

### ISSUE THREAD

**Issue by zombiB** [zombiB/zombi-addons#109]
السلام عليكم، أولا أود أن أشكر كل الاخوة المساهمين في تطوير ماتريكس فمنذ البداية تمنيتها اضافة عربية تشاركية ، و خاصة الأخ @Mr-7mdan الذي أدخل مميزات كثيرة و خصائص جديدة ،تبقى بالنسبة لقسم البث المباشر فأنا امتنعت عن اضافته لماتريكس منذ البداية رغم انني كنت قبلا اعمل على اضافات بث مباشر عربية في كودي او xbmc سابقا عبر اضافاتnavix ، mashupaddon، 
shahid addon.. 
لأسباب مختلفة
اولا  ماتريكس اردتها إضافة مشاهدة حسب الطلب يختار المستعمل البرنامج الذي يريده مسبقا، 
ثانيا روابط البث ليست دائمة و ابقاء القسم شغال يحتاج مجهودات اضافية، الأعضاء أيضا سيطالبون بقنوات أخرى و مواقع بث اخرى ربما ستشكل قلق، أيضا تحول ماتريكس الى إضافة "ستريمينغ" سيعطيها شهرة اضافية و هو سلاح ذو حدين قد يسبب حسب خبرتي المتواضعة مشاكل نحن في غنى عنها، لهذه الأسباب و غيرها أفضل عدم ادماج هذا القسم رغم اني أحببت ما قمت به و أعجبني اللوغو و شعار ماتريكس تيفي، أرجو أن تتقبل رأيي بصدر رحب.

**Comment by Mr-7mdan** [comment]
اخي الكريم، احترم رأيك ورغبتك.
القنوات يتم جلبها من github خاصة يتم الاضافة والتحديث عليها باستمرار حيث انتي استخدمها على جهاز التلفزيون الخاص بي منذ سنين. 
للامر عدة ايجابيات وسلبيات. على اي حال، انا احترم رغبت ولكن هل من الممكن ابقاء الموقع وعدم تفعيلة في الوضع الطبيعي بحيث ان المستخدم العادي لن يدرك وجود القسم. اما الشخص المعني يقوم بتفعيليه من الاعدادات؟ في حال لم يعجبك الاقتراح. فلا مانع اخي من الحذف.

**Comment by zombiB** [comment]
حسنا يمكن اضافته و عدم تفعيله كفترة تجريبية

**Comment by Mr-7mdan** [comment]
تم التعديل الان تحت بند Tools  في اعدادات الاضافة هناك toggle اسمها Enable experimental Features في حال تفعيلها يظهر فقط.

وعندما تكون معطلة، لا يظهر قسم LiveTV في الصفحة الرئيسية ولا يظهر MatrixTV في قسم الـ sources
