### ISSUE TITLE
يوجد مشكلة بالبحث 

### ISSUE THREAD

**Issue by nidaltiti** [zombiB/zombi-addons#117]
ملف بحث لم تظهر النتائج بعض احيان

**Comment by zombiB** [comment]
لازلت لم أجد الخطأ، اصلاح المشكل يحتاج بعض الوقت

**Comment by salahmajali** [comment]
![Uploading image.jpg…]()
![Uploading image.jpg…]()

**Comment by salahmajali** [comment]
نعم لا يوجد نتائج للبحث

**Comment by zombiB** [comment]
> منذ فترة وانا اقوم بتعديل موضوع البحث واضافة البحث عن روابط بشكل مباشر. لا يزال العمل قائماً، لذلك لم اقم بالتحديثات الاخيرة على نسخة التطوير لحين الانتهاء من محاولة تطوير الميزة المذكور اعلاه. احتاج بعض الوقت

البحث عن الروابط المباشرة معقد بعض الشيء لأنه كما تعرف المواقع العربية لا تستعمل نظام واحد، في ماتريكس يوجد خاصية البحث  عبر العنوان في المواقع الأخرى

**Comment by zombiB** [comment]
تم اصلاح مشكلة البحث في النسخة الاخيرة كحل وقتي هل يمكن ان تجرب و تطلعني اذا اشتغل معك

**Comment by nidaltiti** [comment]
ممتاز يا رفقي احنست عملا
