### ISSUE TITLE
 https://wws.brstej.com

### ISSUE THREAD

**Issue by nidaltiti** [zombiB/zombi-addons#125]
وعليكم السلام، يبدو أنك تواجه مشكلة في ملف برستيج (brstej) على الموقع الذي تستخدمه. لكن للأسف، ليس 
 لدي القدرة على وصول الملفات فيدو  لكن  يوجد حلقات  مسلسل

**Comment by zombiB** [comment]
تم اصلاح المشكل في التحديث الأخير
