### ISSUE TITLE
مشكلتان

### ISSUE THREAD

**Issue by nidaltiti** [zombiB/zombi-addons#128]
1.  اختلاط بالحقات واسماء لا يدل لها      يوجد في مسلسلات مثل مسلسل  "بت قبايل"   في الموقع   daktna 

2. يوجد  المشكلة   بالعلامة لتابعة المشاهدة بالفيدو   create bookmark  خاصا الموقع  wecinma   تحمى بشكل تلقائي

**Comment by zombiB** [comment]
شكرا لك على اعلامي بالخطأ سوف أجرب الليلة و أرجع لك

**Comment by zombiB** [comment]
حاولت اصلاح موقع دكتنا جرب التحديث الأخير و اخبرني،
بالنسبة المشكلة الثانية لم أفهم ما تقصد، هل يمكن ان تشرح أكثر

**Comment by nidaltiti** [comment]
المشكلة اولى حلت  
اما بنسبة مشكلة ثانية  قصد        بالانكليزية       Resume  form time      تحمى بشكل تلقائي   خاصتا الموقع   wecinma
