### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ESSAM111111** [zombiB/zombi-addons#130]
All links are not working on Matrix addon with a message no information available, considering that the Internet is connected and other addons are working on Kodi.

**Comment by ESSAM111111** [comment]
How to include the log?

**Comment by ESSAM111111** [comment]
https://paste.kodi.tv/umurewoqow

**Comment by bassemhelal18** [comment]
I think you need a vpn

**Comment by ESSAM111111** [comment]
Yep..from Egypt..I think I need one. Thanks.

**Comment by mohamedsaad208** [comment]
Any recommendations for free VPN?
