### ISSUE TITLE
[BUG] wecima not working 

### ISSUE THREAD

**Issue by Santaklawz** [zombiB/zombi-addons#141]
1-Describe the bug:
The famous wecima site is not working 

Please fix it 
2-Debug log:
go to matrix settings
under tools click on loguploader
than click the upload button
and share the QR code or the URL 

3-Screenshots:if needed

**Comment by zombiB** [comment]
i tested the site and it is working as ususal, may u give more details about the problem your re facing

**Comment by Farid001979** [comment]
ممكن رابط الإضافة ولكم جزيل الشكر

**Comment by Farid001979** [comment]
هل فيه إمكانية لتشغيل الإضافة على stremio أو cloudstream

**Comment by Farid001979** [comment]
> i tested the site and it is working as ususal, may u give more details about the problem your re facing 

مساء الخير خويا

**Comment by Santaklawz** [comment]
> ممكن رابط الإضافة ولكم جزيل الشكر

https://zombib.github.io/

> i tested the site and it is working as ususal, may u give more details about the problem your re facing

When I choose sources wecima or series wecima and then a category like Arabic shows it says no information?

**Comment by Santaklawz** [comment]
> هل فيه إمكانية لتشغيل الإضافة على stremio أو cloudstream

No this is kodi only

**Comment by Santaklawz** [comment]
> i tested the site and it is working as ususal, may u give more details about the problem your re facing
Actually no information is what it says for akwam 
Wecima just does nothing when I click on series or movies i tried it on 2 devices kodi 20.2

**Comment by Santaklawz** [comment]
> i tested the site and it is working as ususal, may u give more details about the problem your re facing

Actually no information is what it says for akwam
Wecima just does nothing when I click on series or movies i tried it on 2 devices kodi 20.2

**Comment by leilaali5555-create** [comment]
الموقع لا يعمل منذ امس
