### ISSUE TITLE
مرحبا موقع فاصل اعلاني اختفى وهو الوحيد الي كان يشتغل😭😭[BUG] 

### ISSUE THREAD

**Issue by AyhamNaji13** [zombiB/zombi-addons#144]
1-Describe the bug:

2-Debug log:
go to matrix settings
under tools click on loguploader
than click the upload button
and share the QR code or the URL 

3-Screenshots:if needed

**Comment by zombiB** [comment]
الرابط القديم لم يعد يشتغل قمت بتغييره يجب أن يعود الى العمل اليوم جرب و أخبرني

**Comment by AyhamNaji13** [comment]
حاولت احط الرابط ما بشتغل على kodi بطلع الرابط فارغ ممكن لو سمحت تحطلي الرابط هون🫶

**Comment by AyhamNaji13** [comment]
https://github.com/zombiB/zombi-addons
هاد بيطلع فاضي

**Comment by zombiB** [comment]
لا ليس عليك تغيير شيء ستعمل الاضافه بشكل عادي
