### ISSUE TITLE
[BUG] does this addon work with kodi 20.3?

### ISSUE THREAD

**Issue by Santaklawz** [zombiB/zombi-addons#145]
Is this excellent addon fully compatible and working with kodi 20.3?

Also I can't get wecima and cimanow sites working?

When I choose the site nothing happens 
Please help me
Also akwam says no information 
What kodi version do you use?

**Comment by zombiB** [comment]
Yes matrix addon works with 20.x versions of kodi
Usually people who have problems to access a site working on my system are those who are living in countries where the sites are blocked, so check on your browser first

**Comment by zombiB** [comment]
I don't use vpn so i can't help you
