### ISSUE TITLE
اقتراح : هل من الممكن اضافة هذا الاضافة لتطبيق Stremio وخصوصاً موقع فاصل اعلاني

### ISSUE THREAD

**Issue by a5rzq** [zombiB/zombi-addons#146]
1-Describe the bug:

2-Debug log:
go to matrix settings
under tools click on loguploader
than click the upload button
and share the QR code or the URL 

3-Screenshots:if needed

**Comment by zombiB** [comment]
I can't do that i am a big fan of kodi from the beginning and i don't want to work on another app
Also i don't know what stremio can do and kodi don't 🤔
