### ISSUE TITLE
[BUG] arabseed next page there but broken 

### ISSUE THREAD

**Issue by Santaklawz** [zombiB/zombi-addons#148]
1-Describe the bug:
The next page on arabseed is there now but keeps repeating the same series 
Wecima and cimanow still not working for me I get no information tried with and without VPN 
What kodi version are you using zombie?
2-Debug log:
go to matrix settings
under tools click on loguploader
than click the upload button
and share the QR code or the URL 

3-Screenshots:if needed

**Comment by zombiB** [comment]
It is not the same series but some series repeat because that is how the website is.

**Comment by Santaklawz** [comment]
Thanks very much bro
