### ISSUE TITLE
البحث يؤدي الى التجميد برنامج كودي

### ISSUE THREAD

**Issue by nidaltiti** [zombiB/zombi-addons#149]
البحث يؤدي الى التجميد برنامج كودي خوصوصا البحث فليم    movie "no way up"    and  " land of bad"  movie

**Comment by zombiB** [comment]
شكرا لك خاصة على وضع امثلة ساجرب الليلة و سأحاول اصلاح الخطأ

**Comment by zombiB** [comment]
قمت بتحديث الاضافة بالأمس،هل يمكنك أن تجرب و تخبرني

**Comment by nidaltiti** [comment]
كل تمام
