### ISSUE TITLE
مشكل في مصدر AKWAM

### ISSUE THREAD

**Issue by eldon33** [zombiB/zombi-addons#15]
مشكور على المجهود لكني لاحظت في التحديث الأخير ان جميع روابط موقع
AKWAM
لم تعد تعمل مع أنها كانت تشتغل بشكل جيد سابقا . الرجاء اصلاحها لو امكن و شكرا

**Comment by zombiB** [comment]
شكرا لك سأعمل عليها اليوم ان شاء الله

**Comment by eldon33** [comment]
مشكور على التفاعل

**Comment by zombiB** [comment]
تم إصلاح الخطأ في النسخة الأخيرة

**Comment by eldon33** [comment]
يعطيك الصحة على المجهود
