### ISSUE TITLE
[BUG]   https://arabseed.show , play error 

### ISSUE THREAD

**Issue by Akkari1988** [zombiB/zombi-addons#152]
![Screenshot 2024-03-07 162224](https://github.com/zombiB/zombi-addons/assets/136963344/7f72611a-a4ad-48b8-95db-b8a4af461b9f)

**Comment by Akkari1988** [comment]
اخي هل العطل من عندي ام من البرنامج ؟

**Comment by zombiB** [comment]
تم اصلاح الموقع مع النسخة الاخيرة
