### ISSUE TITLE
[BUG] the dependency could not be satisfied

### ISSUE THREAD

**Issue by SSnow04** [zombiB/zombi-addons#153]
1-Describe the bug:
When adding the repository to Kodi, the message above appears and the addon doesn't respond.
I tried multiple devices and multiple ways to add it but the same problem appears. 

2-Debug log:
go to matrix settings
under tools click on loguploader
than click the upload button
and share the QR code or the URL 

3-Screenshots:if needed

**Comment by zombiB** [comment]
A log is needed to repair the issue
U can use loguploader addon
