### ISSUE TITLE
مشاكل بالبحث باللغة العربية 

### ISSUE THREAD

**Issue by Memo711mm** [zombiB/zombi-addons#17]
لا يتم البحث باللغة العربية و ياريت تضيف موقع cinemana.me النسخة المجانية

**Comment by zombiB** [comment]
البحث بالعربية يعمل بشكل عادي ، ما هي الكلمة التي بحثت عنها

**Comment by Memo711mm** [comment]
على cima4u كان البحث و جربت اكثر من كلمة و كان موجود عالموقع لكن لم يظهر نتائج

**Comment by zombiB** [comment]
لقد جربت البحث عن كلمة "لعبة" و ظهرت النتائج بشكل عادي في موقع سيمافوريو و المواقع الأخرى
يجب أن تعطيني مثال عن الكلمة التي لم تعمل و تأكد أن لديك آخر نسخة من الاضافة

**Comment by Memo711mm** [comment]
بستخدم احدث اصدار للاضافة 4.2.9  على كودي 18.9  جربت ابحث ( عروس بيروت ) و (رشاش)  (ديدو )  ما ظهرلي اي نتائج بكل الانواع و الافلام و المسلسلات لكن عند البحث عن افلام مثل (tenet) ظهر نتائج طبيعي

**Comment by zombiB** [comment]
جربت البحث عن هذه الكلمات و البحث يعمل جيدا لكنني جربت على النسخة 19 من كودي
أنصحك بالتحديث اذا ممكن

**Comment by Memo711mm** [comment]
انحلت المشكلة
