### ISSUE TITLE
Change Egybest Host

### ISSUE THREAD

**Issue by m7mdcc** [zombiB/zombi-addons#18]
Hi , 

Please Change egybest host to httpsxxxegybest org/

becuse the current url is blocked . :(

**Comment by zombiB** [comment]
Is this adress blocked also : egy. best ?

**Comment by zombiB** [comment]
> > > Yes , another note . I'm using Proxy in kodi "I Configure it in general Internet-Access setting in kodi" . but its not working with your plugin to bypass the block . since I can open blocked website using proxy via chrome .
> > 
> > 
> > I think you should use a vpn addon like openvpn or install a vpn app on your box/pc
> 
> It's should work , but if i don't need vpn for my whole box/pc ? I think in module you can check if global proxy is set or not if set use it . As many other plugins work with my proxy .
> 
> I will stick with your suggestion until we found another solution .
> 
> Another hint , you can make aliases for all host to check if that alias work or not on user network if not use another alisa , you got my point ?
> 
> Thanks

Good ideas, but websites change links many times especially in some countries the best solution is to use a vpn if the user want to
