### ISSUE TITLE
مشاكل المسلسلات 

### ISSUE THREAD

**Issue by Saudi23723** [zombiB/zombi-addons#20]
الرجاء التعديل على البرنامج 
المسلسلات تعرض بشكل مخربط 
و كثير منهم لا يعمل

**Comment by zombiB** [comment]
النسخة الجديدة متوفرة و فيها تحسين و تنظيم للمسلسلات و الحلقات في أغلب المواقع 😊

**Comment by Saudi23723** [comment]
اشكرك جزيل الشكر و جزاك الله كل خير على مجهودك الرائع و تواصلك معنا 💯💯💯
