### ISSUE TITLE
problem kodi 18 avec enigma2

### ISSUE THREAD

**Issue by fagmixy** [zombiB/zombi-addons#21]
salam khouya zombi
je suis fagmixy sur tunisiasat et oussama echifa sur facebook
voici le log de kodi 18 sur enigma2
des hosts comme faselhd, cimaclub, arblionz, shahid4u marche
mais akwam et egybest et d'autre hosts ne marche plus j'ai pas pu tous tester
merci de verifié le log
merci beaucoup

https://www.mediafire.com/file/qg1kp36ewczcm2u/log+kodi+18+for+enigma2.zip/file

**Comment by zombiB** [comment]
شكرا لك لتوفير اللوغ،. للأسف لم أعرف أين يكمن الخطأ هل يمكنك أن تفعل خاصية من الاعدادات
System  - logging - enable debug logging
 ثم ترسل اللوغ من جديد
بعد تجربة المواقع طبعا
مع العلم أني حملت نسخة ١٨ من كودي و المواقع تعمل جيدا على ويندوز

**Comment by potogo** [comment]
سوف أجرب المواقع جميعها و أرسل لك اللوغ من جديد المشكلة ان مواقع مثل اكوام و آجيبيست تعمل فقط الروابط لا تظهر 
نعم هذا ما حيرني على ويندوز يعمل كودي 18
سأعاود إرسال اللوغ

**Comment by fagmixy** [comment]
سوف أجرب المواقع جميعها و أرسل لك اللوغ من جديد المشكلة ان مواقع مثل اكوام و آجيبيست تعمل لك الروابط لا تظهر ؤ
نعم هذا ما حيرني على ويندوز يعمل كودي 18
سأعاود إرسال اللوغ
شكرا لك

**Comment by fagmixy** [comment]
تفضل اللوغ
https://www.mediafire.com/file/bs5umltud3j5hu2/kodi.log/file
عرب ليونز، أكوام القديم، فاصل إعلاني، شاهد فور يو، عرب سيد، فجر تيفي... جميعها تعمل
المشكل مع اكوام و إجي بيست
على اكوام تظهر فقط روابط التحميل و لا تظهر روابط المشاهدة و عند الضغط على روابط التحميل لا يحدث شيء تظهر العجلة و تختغي 
أما إجي بيست عند الضغط على إسم الفيلم تظهر العجلة تبقى تدور ثم تختفي بدون حدوث شيء
شكرا لك
