### ISSUE TITLE
Aflamfree, e7na, rotanavod

### ISSUE THREAD

**Issue by fagmixy** [zombiB/zombi-addons#22]
السلام عليك اخي زومبي
لو ممكن إصلاح 
Nextpage
على موقع aflamfree حيث عند الدخول لقسم pack و إختيار موقع aflamfree داخل اقسام أفلام اجنبية او عربية او 
 أسيوية... رغم آحتواء الموقع على مكتبة ضخمة من الأفلام لا تظهر nextpage و في بعض الأقسام تظهر لغاية الصفحة 3
الموقع مهم جدا لانه يعرض الأفلام القديمة و النادرة ى
و موقع e7na لا تظهر أفيشات الأفلام
و لو ممكن النظر في موقع روتانا حيث إشترو حقوق الأفلام العربية القديمة و بدؤو بحدفها على يوتوب و عرضها على موقعهم الرسمي بسيرفر سريع و متعدد الجودات
وشكرا

**Comment by zombiB** [comment]
- [ ] إصلاح Nextpage على موقع aflamfree
- [ ] موقع e7na لا تظهر أفيشات الأفلام
- [ ] موقع روتانا
