### ISSUE TITLE
How can I find movies dubbed in arabic? 

### ISSUE THREAD

**Issue by Stivan101** [zombiB/zombi-addons#24]
How can I find movies dubbed in arabic? When I search for dubbed I only find movies for Kids but I want normal Cinema movies. And many Websites do not work im using dns 8.8.8.8
I search for Real dub and not fake dub

**Comment by zombiB** [comment]
Sadly Movies are not dubbed in arabic systematically, only animation movies or some Disney live actions movies are dubbed frequently
You can find maybe 10 or so old movies which were dubbed by mbc like avatar or the gladiator those movies are rare but u can find them on dubbed movies section under movies
Turkish movies are generally dubbed in arabic and re found on Turkish movies section
You can find also old movies dubbed in Arabic or Egyptian dialect on shoofvod website in English movies section but the majority of links are dead
