### ISSUE TITLE
provide help

### ISSUE THREAD

**Issue by emadmahdi** [zombiB/zombi-addons#26]
Hi ... I am the author of "plugin.videos.arabicvideos" ... If you need any help from me or my addon then please do not hesitate to ask ... I will be glad to provide help/parts of my scripts if needed.

**Comment by emadmahdi** [comment]
These are my websites:
.
http://tiny.cc/kodiemad
http://kodirepo.uk.to

**Comment by zombiB** [comment]
Thank you for your generous offer, feel free to share your suggestions, edits or fixes on pull request section 😊
