### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Waleed-titi** [zombiB/zombi-addons#36]
* [ ] Are you running the latest version? Yes

**Describe the bug**
Egy best site  on the  addon is not working i see all the movies and series but when i try to open it,it gives me an error , although i have another version on my android tv and it's working perfect .  !!!

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

## Debug log

[First of all thanks for making the effort to report an issue, reporting issues is critical to improve the project quality]
[Please include a link to your full debug log. Follow these instructions https://github.com/arvvoid/plugin.video.hbogoeu/wiki/Debug-log]

[Please note, bug reports without full logs will be marked as ignored rules and ignored untill a log is provided]

**Screenshots**
![IMG_20220210_075206](https://user-images.githubusercontent.com/99385474/153350545-2554b30a-c070-4240-993b-aec702ba184f.jpg)

**Operating System**
* [ ] Android

**Additional informatin on the environment**

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

**Additional context**

**Comment by zombiB** [comment]
It was due to tiers app blocking access.
