### ISSUE TITLE
Tuktukcinema english series no informations

### ISSUE THREAD

**Issue by Saudi23723** [zombiB/zombi-addons#37]
السلام عليكم  اخي الكريم 
الرجاء إصلاح  Tuktukcinema  على البرامج التلفزيون  الأجنبية حيث انه لا يوجد أي معلومات عند الدخول على اي حلقة على اي مسلسل و شكرا

**Comment by zombiB** [comment]
و عليكم السلام ورحمة الله شكرا لاعلامي بالخطأ   تم تحديث الموقع

**Comment by Saudi23723** [comment]
اخي  الكريم لم  يتم التحديث للأسف الرجاء الاطلاع على نفس المشكلة 
![1645714464186300931617421834249](https://user-images.githubusercontent.com/92276709/155548306-7a0452c3-0c7a-4f5a-ac24-da7b1f5de32f.jpg)

**Comment by zombiB** [comment]
> اخي الكريم لم يتم التحديث للأسف الرجاء الاطلاع على نفس المشكلة ![1645714464186300931617421834249](https://user-images.githubusercontent.com/92276709/155548306-7a0452c3-0c7a-4f5a-ac24-da7b1f5de32f.jpg)

غريب الموقع يعمل  جيدا بعد التحديث هل يمكنك أن تجرب من جديد

**Comment by Saudi23723** [comment]
نعم عزيزي قبل كم يوم اشتغل و الأمور ١٠٠/١٠٠
اشكر تعاونك و ردك على كل إستفسار
