### ISSUE TITLE
توك توك سينما tuktukcinema 

### ISSUE THREAD

**Issue by Saudi23723** [zombiB/zombi-addons#40]
السلام عليكم اخي الكريم 
عادت مشكلة عدم ظهور حلقات المسلسلات على هاد الموقع 
حيث عند الضغط على الحلقة يخرج اشعار بعدم وجود معلومات و هو على كل المسلسلات 
![16484070638958597607955176496356](https://user-images.githubusercontent.com/92276709/160296191-fcc5af79-3802-4885-8531-e36770c7d9fb.jpg)

**Comment by zombiB** [comment]
شكرا لاعلامي بالخطأ تم تحديث الموقع

**Comment by Saudi23723** [comment]
اخي الكريم احاول ان أضيف السورس من جديد على التلفزيون لكن لا يعمل
https://zombib.github.io/zip/
 ما هي المشكلة الرجاء الرد

**Comment by Saudi23723** [comment]
السلام عليكم اخي الكريم
المسلسلات العربية لا تعمل ولا على اي موقع الرجاء التحديث
و شكرا
