### ISSUE TITLE
اضافة السورس 

### ISSUE THREAD

**Issue by Saudi23723** [zombiB/zombi-addons#41]
اخي الكريم احاول ان أضيف السورس من جديد على التلفزيون لكن لا يعمل 
https://zombib.github.io/zip/ 
 ما هي المشكلة الرجاء الرد

**Comment by Saudi23723** [comment]
![16493912837483963105547718280796](https://user-images.githubusercontent.com/92276709/162361241-d13bdee1-3964-47d1-bc5b-a2f21e249297.jpg)

**Comment by zombiB** [comment]
استعمل الرابط الجديد https://zombib.github.io/

**Comment by Saudi23723** [comment]
شكرا جزيلا عزيزي
