### ISSUE TITLE
البحث لايشتغل

### ISSUE THREAD

**Issue by Mo-schneider** [zombiB/zombi-addons#42]
أنا أستعمل آخر إصدار من الإضافة، منذ مدة كانت تعمل بدون مشاكل
المشكل الأول: خاصية البحث لا تعمل، بعد كتابة الكلمات المراد البحث عنها، تنبثق نا فذة على أساس أن البحث جاري لكن عملية البحث في الحقيقة لا تتم.
المشكل الثاني : خاصية إضافة الفيديوهات إلى المفضلة لا تعمل أيضا
بالإضافة الى انه أغلب المواقع أصبحت لا تعمل فقط البعض منها
طلب إضافي : هل من الممكن إضافة إمكانية البحث عن طريق السنة.
شكرا جزيلا.

**Comment by zombiB** [comment]
مرحبا بك أخي الكريم، اي نسخة من كودي تستعمل؟

**Comment by zombiB** [comment]
للحصول على كل مميزات الاضافة يجب تحميل كودي 19

**Comment by zombiB** [comment]
بالنسبة للبحث عن طريق السنة فهو موجود في قسم افلام years و سيتم اضافة مواقع اخرى

**Comment by Mo-schneider** [comment]
مفهوم، شكرا جزيلا
