### ISSUE TITLE
Akwam

### ISSUE THREAD

**Issue by bassemhelal18** [zombiB/zombi-addons#43]
موقع اكوام عند الوصول الي تشغيل الفيديو لا يعمل يظهر watch - downlaod 
وعند الضغط علي watch تظهر رساله no information
اخر تحديث 5.0.6
شكرا جزيلا لك

**Comment by zombiB** [comment]
تم إصلاح الموقع في النسخة الأخيرة جرب و ابلغني

**Comment by bassemhelal18** [comment]
شكرا جزيلا لك و بالتوفيق دائما
