### ISSUE TITLE
المسلسلات العربية 

### ISSUE THREAD

**Issue by Saudi23723** [zombiB/zombi-addons#45]
السلام عليكم اخي الكريم 
الرجاء التحديث المسلسلات العربية كلها لا تعمل ولا يوجد معلومات على اي موقع ولا على مسلسلات رمضان للأسف 
![16508431792576248723554050207230](https://user-images.githubusercontent.com/92276709/165001255-40d96719-44bd-4ae1-896f-d4ecc2f3d95c.jpg)

**Comment by zombiB** [comment]
و عليكم السلام أخي العزيز، المواقع تعمل جيدا لدي في قسم مسلسلات عربي و قسم رمضان،. ربما المواقع محجوبة في منطقتك
