### ISSUE TITLE
OK.RU

### ISSUE THREAD

**Issue by midozalouk** [zombiB/zombi-addons#52]
Could you please provide praser for mobile.ok.ru
as ok.ru is prohibited in Egypt
thanks

**Comment by midozalouk** [comment]
The video url is the one with
data-objid="xxx"

while xxx is the videoid

**Comment by zombiB** [comment]
Okey thanks i will try to add it

**Comment by zombiB** [comment]
Hi websites don't use mobile.ok.ru maybe u should use other hosters
