### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jasonalshamary** [zombiB/zombi-addons#61]
السلام عليكم اخي حلفتك بالله وغلات الوالده عندك
علمني كيف اعمل add on 
مثل الي عامله سنوات وانا احاول حتي لو ادفعلك انا حاظر
رد علي حلفتك براس من اغلا احبابك

**Comment by jasonalshamary** [comment]
ايميلي

jasonalshammary
hotmail
.com

**Comment by jasonalshamary** [comment]
Hello are you there?

**Comment by jasonalshamary** [comment]
السلام عليكم وينك حبيبي 
موجود ؟؟؟؟؟؟؟

**Comment by zombiB** [comment]
مرحبا اخي الحقيقة انا لست مطور محترف انا تعلمت من خلال قراءة الكود و التعديل على اضافات اجنبية حاضرة انصحك اولا بأخذ كورس بيثون اونلاين موجود دروس مجانية لتفهم اساسيات الكود ثم اختار اضافة معينة و قم بتجربة تغيير الكود

**Comment by jasonalshamary** [comment]
عندي شوي فكره بس ساعدني
شوي انا مستعد ادفعلك بالله عليك
خليك معي

Sent from my iPhone

On Jan 12, 2023, at 10:04 PM, zombiB ***@***.***> wrote:

﻿

مرحبا اخي الحقيقة انا لست مطور محترف انا تعلمت من خلال قراءة الكود و التعديل على اضافات اجنبية حاضرة انصحك اولا بأخذ كورس بيثون اونلاين موجود دروس مجانية لتفهم اساسيات الكود ثم اختار اضافة معينة و قم بتجربة تغيير الكود

**Comment by jasonalshamary** [comment]
فرجيني انت كيف سويت
وخلي الباقي عليي انا شفت انت حاط صور في المنتدي بس ما اقدر اشوفهم لاني مو مشترك ولا اقدر اشترك بالله علمني الي انت تعرفه

Sent from my iPhone

On Jan 12, 2023, at 10:04 PM, zombiB ***@***.***> wrote:

﻿

مرحبا اخي الحقيقة انا لست مطور محترف انا تعلمت من خلال قراءة الكود و التعديل على اضافات اجنبية حاضرة انصحك اولا بأخذ كورس بيثون اونلاين موجود دروس مجانية لتفهم اساسيات الكود ثم اختار اضافة معينة و قم بتجربة تغيير الكود

**Comment by zombiB** [comment]
الصور في المنتدى هي فقط لكيفية اضافة موقع في ماتريكس
اذا انت تريد انشاء addon خاص بك يجب ان تكون ملم بأساسيات بايثون 
انصحك بمتابعة درس على النت يوجد مواقع مجانية و مدفوعة 
مثال : https://www.learnpython.org/

**Comment by jasonalshamary** [comment]
ههههههه ليش ادفع للغريب انت اخي
ادفعلك انت
صح؟

Sent from my iPhone

On Jan 13, 2023, at 10:10 AM, zombiB ***@***.***> wrote:

﻿

الصور في المنتدى هي فقط لكيفية اضافة موقع في ماتريكس
اذا انت تريد انشاء addon خاص بك يجب ان تكون ملم بأساسيات بايثون
انصحك بمتابعة درس على النت يوجد مواقع مجانية و مدفوعة
مثال : https://www.learnpython.org/

**Comment by jasonalshamary** [comment]
مثل الي عندك بضبط
مثلن موقع اكوام

https://akwam.to/

من وين تبدا في
من اي مكان تقطع فاهمني ؟
زي addon تبعك انت والله ادفعلك انا حاظر خليك معاي ساعدني
وانا عندي اكواد Visual basic نفس الفكره بس علي الكبيوتر ابعثلك كل السورسات اذا تحب
شو رايك تكلمني واتساب تفيدني و فيدك ؟
Sent from my iPhone

On Jan 13, 2023, at 4:07 PM, zombiB ***@***.***> wrote:

﻿

شكرا اخي على كرمك ، انت لماذا تريد ان تعمل addon ؟ ما هو المحتوى الذي تريد ان تقدمه؟

**Comment by jasonalshamary** [comment]
انا من زمان حاب اتعلم
بس مو انو انشر لا بس خاص فيني و اهلي لا اكثر

Sent from my iPhone

On Jan 13, 2023, at 4:14 PM, jason alshammary ***@***.***> wrote:

﻿
مثل الي عندك بضبط
مثلن موقع اكوام

https://akwam.to/

من وين تبدا في
من اي مكان تقطع فاهمني ؟
زي addon تبعك انت والله ادفعلك انا حاظر خليك معاي ساعدني
وانا عندي اكواد Visual basic نفس الفكره بس علي الكبيوتر ابعثلك كل السورسات اذا تحب
شو رايك تكلمني واتساب تفيدني و فيدك ؟
Sent from my iPhone

On Jan 13, 2023, at 4:07 PM, zombiB ***@***.***> wrote:

﻿

شكرا اخي على كرمك ، انت لماذا تريد ان تعمل addon ؟ ما هو المحتوى الذي تريد ان تقدمه؟

**Comment by zombiB** [comment]
آسف اخي لا استطيع مساعدتك فليس لدي المعرفة اللازمة

**Comment by jasonalshamary** [comment]
اوكي حبيبي شكرا و اسف علي الازعاج

Sent from my iPhone

On Jan 13, 2023, at 4:35 PM, zombiB ***@***.***> wrote:

﻿

Closed #61<https://github.com/zombiB/zombi-addons/issues/61> as completed.
