### ISSUE TITLE
[BUG] عدم ظهور روابط قصة عشق مرة اخرى 

### ISSUE THREAD

**Issue by Waleed-titi** [zombiB/zombi-addons#70]
السلام عليكم اخى زومبى 
منذ يومان بالضبط روابط مشاهدة  موقع قصة عشق عادت مرة اخر لعدم الظهور و عند الدخول على اى شىء يعطى no information ممكن تلقى نظرة على الامر من فضلك ممكن تكون حاجة بسيطة و شكرا جزيلا لك .

**Comment by zombiB** [comment]
حسنا سأحاول اصلاحها

**Comment by Waleed-titi** [comment]
1_هناك ايضا امر اخر كنت اتناقش مع الاخ يونس منذ قليل موقع فاصل hd  هذا لغز كبير الموقع يفتح معى عادى  على الاضافة و الروابط تعمل معى تمام و لكن عند تشغيل vpn  المواقع لا يفتح معى ابدا و يعطيني no information على الاضافة و يعطينى رسالة  انه محمى بكلاود فلير مع ان الموقع يفتح عادى بنفس ال vpn على المتصفح بدون اى مشاكل  فاستنتجت انه يعمل فى مصر فقط و لكن الاخ يونس جرب يدخل عليه من على الإضافة و فتح معاه و لم يعطيه no information  و يرى الروابط ايضا و عند فتحى لفيلم من عليه فتح معى بس طبعا بدون vpn  و لكن عندما جرب الاخ يونس نفس الفيلم و جرب يشغله من الرابط لم يعمل معه مع انه فتح معى الفيلم عادى فما هو التفسير لهذا اللغز 
2- موقع موفيز لاند لا يفتح على الاضافة مع انه لم يغير الرابط مازال كما هو  movizland.xyz  و موقع ماى سيما غير الرابط ل https://wecimaa.click
