### ISSUE TITLE
please fix Movizland

### ISSUE THREAD

**Issue by samirinhoo** [zombiB/zombi-addons#83]
Hi bro ,
-MovizLand shows No link valid , plez fix..
- most of sites that should show and run WWE wrestling Events ,doesn't show any WWE  wrestling  event or link , always display
 "no information" can you fix this bug please 
THANK YOU

**Comment by zombiB** [comment]
Hi
Thank you for sharing, movizland is fixed now and arabseed is added to the wwe section

**Comment by samirinhoo** [comment]
Please if u can have a look on arablionz file it has issue showing categories including WWE not same as browsing site . Thanx
