### ISSUE TITLE
categories issues

### ISSUE THREAD

**Issue by samirinhoo** [zombiB/zombi-addons#86]
Hi , sites ( movizland , cimaclub , stardima ) >> movie categories not showing movies , plez check issue and fix , thanx

**Comment by samirinhoo** [comment]
Please add shahid4u site » https://shahid4uu.co/

**Comment by zombiB** [comment]
Sorry for the late reply i tried to fix movizland and cimaclub but i didn't look at stardima movie section maybe next time
