### ISSUE TITLE
please add these streaming link servers

### ISSUE THREAD

**Issue by samirinhoo** [zombiB/zombi-addons#87]
some new streaming video servers for @rb$eed ( streamwish.to , filelions.to , vidello.net ) please add them

**Comment by zombiB** [comment]
Thank you for the suggestion i have less time to check the sites and you re making gain time 😊 so i added two servers, i couldn't find a link for videlo if u know an item that have it share it with me and i will try to add it

**Comment by samirinhoo** [comment]
Hi bro. Thanx for adding servers. Vidello server seems not appearing anymore in recent movies and series. If I notice it I will share it's link. regarding ( cimaclub-drkvid ) video server still not playing video please can you have a look & try to fix. Thanx

**Comment by zombiB** [comment]
Unfortunately i can't make the cimaclub server work hopefully soon i will find a way

**Comment by zombiB** [comment]
Cimaclub club server is fixed now
