### ISSUE TITLE
Arabic language doesn't work anymore[BUG] 

### ISSUE THREAD

**Issue by flavasava2022** [zombiB/zombi-addons#88]
Arabic language doesn't work anymore

**Comment by zombiB** [comment]
What do you mean?

**Comment by flavasava2022** [comment]
In search or when the name of the content in arabic
![Screenshot_2023-06-11-23-20-22-608_org xbmc kodi](https://github.com/zombiB/zombi-addons/assets/112499614/8d05f368-2227-4888-8e26-3af6e91ecc6c)

**Comment by flavasava2022** [comment]
My mistake it was a big in kodi,thanks.
