### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kvrim1** [zombiB/zombi-addons#89]
* [Yes] Are you running the latest version?

![image](https://github.com/zombiB/zombi-addons/assets/136848366/3443da19-8a9f-425a-b38c-ae5fa95cb475)

احل الموضوع ده ازاي؟

**Operating System**
Windows (x64)

**Comment by zombiB** [comment]
Sorry for the late reply i updated the repository try again and confirm

**Comment by kvrim1** [comment]
Installed and working now thank you for helping❤
