### ISSUE TITLE
[BUG] Could not connect to repository

### ISSUE THREAD

**Issue by shiiheb** [zombiB/zombi-addons#91]
* [x ] Are you running the latest version?

**Describe the bug**
I could not install Zombi repository and it seems to be a common issue. 
I am using Kodi V20.2

**To Reproduce**
Steps to reproduce the behaviour:
1. I added this source https://zombib.github.io
2. I installed the repo from the zip file. it was added successfully as the notification affirm
3. I tried to install the repo from the repository, but I got this error: "Could not connect the repository" (I tried to reinstall Kodi, added the source again without success)

**Screenshots**
![278813081_2198542043630829_2749542033054589029_n](https://github.com/zombiB/zombi-addons/assets/75363752/81255eae-8ccf-43f4-be4a-64f821c0f179)

This screenshot is from the internet but it contains exactly the same interface and the words on my screen. 

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

**Additional informatin on the environment**

Android V9, TV TCL 
Kodi 20.2

Is there any additional link for the repository that could resolve the issue? or any manipulation to make to overcome this error? Could I provide any further information to help you to figure out the issue?

**Comment by zombiB** [comment]
Thanks for sharing pb is fixed today plz try again and confirm

**Comment by shiiheb** [comment]
Thank you, it works now.
